[package]
name = "multi-skill"
version = "0.1.2"
authors = ["Aram Ebtekar <aramebtech@gmail.com>"]
edition = "2018"

description = "Skill estimation systems for multiplayer competitions"
repository = "https://github.com/EbTech/Elo-MMR"
readme = "../README.md"
keywords = ["skill", "rating", "estimation", "competition", "bayesian"]
categories = ["algorithms", "mathematics", "game-development"]
license = "MIT"

[dependencies]
rayon = "1.5"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
statrs = "0.13"
overload = "0.1"
float-cmp = "0.8"
csv = "1.1"
select = "0.6.0-alpha"
superslice = "1.0"

[[bin]]
name = "rate"

[[bin]]
name = "eval"

[[bin]]
name = "hparam_search"

[[bin]]
name = "dance"

[[bin]]
name = "adversary"
